---
title: "R4MarineScience_01"
subtitle: "Foundations of Data Science: Wrangling and Plotting"
author: Kylah Kalbfleisch
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
#Execute workshop 1 script
source("../code/R4MarineScience_01.R")
```

```{r}
#Pipe directly from aggregation to plotting with error bars
mass_compare_plot <- penguins |>
  group_by(species, island) |>
  summarise(
    mean_mass = mean(body_mass_g, na.rm = TRUE),
    sd_mass = sd(body_mass_g, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  ) |>
  ggplot(aes(x = species, y = mean_mass, colour = island)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = mean_mass - sd_mass,
                    ymax = mean_mass + sd_mass),
                width = 0.2) +
  labs(title = "Mean Body Mass by Species and Island",
       subtitle = "Error bars represent standard deviation",
       y = "Mean Body Mass (g)",
       x = "Species") +
  theme_minimal()

mass_compare_plot
```

```{r}
#Experiment with swapping sd_mass for standard error
mass_compare_se_plot <- penguins |>
  group_by(species, island) |>
  summarise(
    mean_mass = mean(body_mass_g, na.rm = TRUE),
    sd_mass = sd(body_mass_g, na.rm = TRUE),
    n = n(),
    se_mass = sd_mass / sqrt(n),
    .groups = "drop"
  ) |>
  ggplot(aes(x = species, y = mean_mass, colour = island)) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(
      ymin = mean_mass - se_mass,
      ymax = mean_mass + se_mass
    ),
    width = 0.2
  ) +
  labs(
    title = "Mean Body Mass by Species and Island",
    subtitle = "Error bars represent standard error",
    y = "Mean Body Mass (g)",
    x = "Species"
  ) +
  theme_minimal()

mass_compare_se_plot
```

```{r}
#Create output directories if they do not exist:
if (!dir.exists("../outputs/figures")) dir.create("../outputs/figures")
if (!dir.exists("../outputs/tables")) dir.create("../outputs/tables")
if (!dir.exists("../Rdata")) dir.create("../Rdata")
```

```{r}
#Save table
write_csv(biological_signal, "../outputs/tables/penguin_species_mass_summary.csv")
```

```{r}
#Save figure 
ggsave("../outputs/figures/mass_compare_plot.png", 
       plot = mass_compare_plot, 
       width = 120, height = 120, 
       units = "mm", dpi = 300)

```
